import { NextResponse, type NextRequest } from "next/server";
import { defaultLocale, isLocale } from "@/lib/i18n";

/**
 * Locale rewriting.
 *
 * This is Next 16's `proxy` convention — the file formerly known as
 * `middleware.ts`, renamed upstream.
 *
 * Routes live under `app/[locale]/`, but French must stay unprefixed so every
 * existing URL keeps working. This rewrites (never redirects) an unprefixed
 * path onto the French segment:
 *
 *   /apply     → renders /fr/apply, URL stays /apply
 *   /en/apply  → untouched
 *
 * A rewrite rather than a redirect means the statically generated `/fr/…` page
 * is served directly — no extra round trip, and the browser URL never gains a
 * visible `/fr`.
 *
 * There is deliberately no `Accept-Language` redirect. Auto-switching language
 * on a marketing site sends a visitor somewhere they did not ask to go, splits
 * ad-campaign landing data, and makes crawlers see a different page than the
 * one they requested. The toggle in the navigation is the only way to change
 * language, and the choice is expressed in the URL.
 */
export function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const first = pathname.split("/").filter(Boolean)[0];
  if (first && isLocale(first)) return NextResponse.next();

  const url = request.nextUrl.clone();
  url.pathname = `/${defaultLocale}${pathname === "/" ? "" : pathname}`;

  return NextResponse.rewrite(url);
}

export const config = {
  /**
   * Everything except API routes, Next internals and the files served from
   * /public or generated by the metadata API. Those must not gain a locale
   * segment — `/sitemap.xml` is `/sitemap.xml` in both languages.
   */
  matcher: [
    "/((?!api|_next/static|_next/image|icon.svg|favicon.ico|robots.txt|sitemap.xml|manifest.webmanifest|opengraph-image|media/|.*\\.(?:webp|jpg|jpeg|png|svg|mp4|webm|ico|txt|xml|webmanifest)$).*)",
  ],
};
